add specs for features in the add / edit product page
PrestaShop/prestashop-specs pull request #159
Opened 2020-10-21 11:58 UTC by marionf

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | add specs for features in the add / edit product page

2020-10-21 12:24 UTC, Robin-Fischer-PS requested changes
Features are displayed by position, but the number displayed (if several features have the same name) is not the position, but the ID of the feature.
See the ID and Position number here : 
![Id on product feature](https://user-images.githubusercontent.com/55688534/96718468-5b2c5e80-13a8-11eb-8338-bb41357cbb5d.png)

On Product page, it's the ID that is shown
![Id on product](https://user-images.githubusercontent.com/55688534/96718471-5c5d8b80-13a8-11eb-976d-ce0167e39684.png)

And on a different but similar subject, this behavior also happens when several brands have the same name, the ID is displayed : 
![same behavior brand](https://user-images.githubusercontent.com/55688534/96718696-a9d9f880-13a8-11eb-8fa9-64abc5ce2852.png)

2020-10-21 12:24 UTC, Robin-Fischer-PS commented on back-office/catalog/products/catalog-products-add-edit.md
> +If there are several features with the same name, then the position of the feature is displayed before its name
```suggestion
If there are several features with the same name, then the ID of the feature is displayed before its name 
```

2020-10-21 12:30 UTC, marionf commented
I didn't know for the brands, I just updated this part also :)

2020-10-21 16:18 UTC, Robin-Fischer-PS approved these changes

2020-10-22 09:39 UTC, LouiseBonnard approved these changes

2020-10-22 12:10 UTC, merged