Update Order Page View.md
PrestaShop/prestashop-specs pull request #167
Opened 2020-11-02 17:40 UTC by MatShir

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Currently, the product list displays the product by the order in which the products are added to the cart. So the first page of the product list into the order page is the first one to be added and the last page on the product list displays the latest products added. <br /><br />A product added through the BO's order page was displayed on the page where the product was added and then displayed at the end after a refresh. Now, with the new refresh system of the product list, the user won't know if the product is successfully added since the product will be added directly on the last page. <br /><br />So, to bring more awareness to the user, when a product is added, the page will display a success alert. The product list will now display the product by the order anti chronological, the latest product added to the cart are the first one to be displayed.
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/21500

2020-11-19 09:24 UTC, marionf commented
Hey @MatShir Could you resolve the conflicts before the review please ?

2021-01-13 01:36 UTC, MatShir commented
Conflict resolved! Can I merge it? @marionf

2021-01-14 10:39 UTC, marionf requested changes
Just some suggestions

2021-01-14 10:39 UTC, marionf commented on back-office/orders/orders/Order Page View.md
> +[Edit/Change Adresse behaviors](https://invis.io/YKTGGFZAMCB#/386397109_Edit_Adress)
```suggestion
[Edit/Change Addresse behaviors](https://invis.io/YKTGGFZAMCB#/386397109_Edit_Adress)
```

2021-01-14 10:39 UTC, marionf commented on back-office/orders/orders/Order Page View.md
> +Then the product list is refreshed behind the loading spinner to check if any gift product has to be removed as well. The user is redirected to the page where the user removed the product. If the rem
```suggestion
Then the product list is refreshed behind the loading spinner to check if any gift product has to be removed as well. The user is redirected to the page where he/she was when he/she removed the product. If the removed product was on the last page, the user is redirected to the second-last page.
```

2021-01-14 10:39 UTC, marionf commented on back-office/orders/orders/Order Page View.md
> +On the bottom of the bock, there is the **Order comment**. The order comment saves a comment for the corresponding order. It is closed by default when it is empty and open when filled. To add a comme
```suggestion
On the bottom of the block, there is the **Order comment**. The order comment saves a comment for the corresponding order. It is closed by default when it is empty and open when filled. To add a comment when it is empty, the user has to click on the + button and has to press the save button to save it.
```

2021-01-14 10:39 UTC, marionf commented on back-office/orders/orders/Order Page View.md
> +If the shop has different currencies, a droplist of the shop's currencies is displayed to change the order currency. The change rate is based on the latest conversion rate save by the shop.
```suggestion
If the shop has different currencies, a droplist of the shop's currencies is displayed to change the order currency. The change rate is based on the latest conversion rate saved in the shop.
```

2021-01-20 13:21 UTC, merged

2021-01-20 13:21 UTC, MatShir commented
Thanks @marionf