Tags specs
PrestaShop/prestashop-specs pull request #268
Opened 2021-11-18 15:51 UTC by Saimis777

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2021-11-22 09:44 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +title: Add / Edit Store
```suggestion
title: Add / Edit tag
```

2021-11-22 09:44 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +# Add / Edit tags
```suggestion
# Add / Edit tag
```

2021-11-22 09:45 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +While adding or editing tags, the following fields/drop downs/parameters are displayed:
```suggestion
While adding or editing a tag, the following fields/drop downs/parameters are displayed:
```

2021-11-22 09:47 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +This field is for the name of the tag, the field is mandatory. When trying to save without any name input, shows the message: "The name field is required."
```suggestion
This field allows to fill the name of the tag and is mandatory. If the save button is pressed and if this field is empty, the following error message is displayed: "The name field is required."
```

2021-11-22 09:49 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +This is a drop-down menu for the language of the tag. The default country (selected in International > Localization > Configuration) is selected by default.
```suggestion
This drop-down menu allows selecting the language of the tag. The default country (selected in International > Localization > Configuration) is selected by default.
```

2021-11-22 09:51 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +
The countries listed in the drop-down are the countries enabled in International > Localization > Languages

2021-11-22 11:13 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/index.md
> +---
The "_" is missing before the index.md

2021-11-22 12:38 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +This section has 2 fields, the one on the left indicates all the products that are added to the shop, and has a button below the list named: "Add". When selecting a product, and pressing "add" the se
```suggestion
This section allows to select products associated with the tag and has 2 parts:
- the one on the left lists all the products of the shop
- the one on the right lists all the products selected for the tag.
 When selecting a product, and clicking on "add", the selected product moves to the right box.
The user can select several products and add them to this tag at once.
```

2021-11-22 12:40 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +From the field box o the right, you can also select the products, and press "remove" which is below the field, then the product is moved back to the left field box.
```suggestion
When selecting a product in the list on the right, and clicking on "remove", the selected product is moved back to the left box.
```

2021-11-22 14:24 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md
> +---
Can you rename content/1.7/back-office/shop-parameters/search/tags/add-edit-tags.md by content/1.7/back-office/shop-parameters/search/tags/add-edit-tag.md as you add and edit only one tag, the S should be removed

2021-11-22 14:31 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +The tagging feature enables to associate products with keywords. Customers can use the keywords to easily and quickly find the products they are looking for.
```suggestion
The tagging feature allows associating products with keywords. Customers can use the keywords to easily and quickly find the products they are looking for.
```

2021-11-22 16:15 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +## Multistore
This whole part is wrong, there is no shop association block while creating or editing a tag, so it's added for all shops and then the lists displays all the tags no matter the context

2021-11-22 16:16 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +ID number of the tag.
```suggestion
ID of the tag.
```

2021-11-22 16:17 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +## Columns
For this part, the search and sort part are missing

2021-11-22 16:20 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +  After clicking on "Delete" button, the store is deleted and a successful message is displayed "Successful deletion."
```suggestion
  After clicking on "Delete" button, the tag is deleted and a successful message is displayed "Successful deletion."
```

2021-11-22 16:21 UTC, marionf requested changes
I let you see my comments and suggestions, let me know if you have questions

2021-11-23 14:18 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +Creating or editing a tag, it's added for all shops and then the lists displays all the tags no matter the context selected.
```suggestion
While creating or editing a tag, it's added or edited for all shops (no matter the context selected). So, the list displays all the tags, no matter the context selected.
👉 See [the specs](../../../../../broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-2-add-new-pages-without-shop-association-block)
```

2021-11-23 14:21 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +## Columns
Could you specify for each columns if a search or a sort is possible ?

2021-11-23 14:26 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/add-edit-tag.md
> +In the case of adding a new tag, the tag is added and a success message is displayed on the tags listing: "Successful creation.". In the case of editing a tag, the tag is edited and a success message
```suggestion
In the case of adding a new tag and if there is no error, the tag is added and a success message is displayed on the tags listing: "Successful creation.". In the case of editing a tag and if there is no error, the tag is edited and a success message is displayed on the tags listing: "Successful update.".
```

2021-11-23 15:14 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +
```suggestion
The Bulk actions button is enabled only if at least one row of the list is selected.
```

2021-11-25 08:22 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +👉 See [the specs](../../../../../broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-2-add-new-pages-without-shop-association-block)
This link seems wrong, could you fix it ?

2021-11-25 08:24 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +The search button is disabled as long as there are less than 2 tags in the list. Search can be used for ID, language, name and Products.
```suggestion
The search button is disabled as long as there are less than 2 tags in the list. A search can be done by ID, language, name, and Products.
```

2021-11-25 08:25 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +It's possible to sort the list by pressing the arrow button near ID, language, name or products.
```suggestion
It's possible to sort the list by ID, language, name or products in an ascending or descending way.
```

2021-11-25 09:58 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +👉 See [the specs](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-2-add-new-pages-without-shop-associa
We should use relatives links rather than absolutes links

2021-11-25 15:53 UTC, marionf approved these changes

2021-11-29 17:19 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +Clicking on the _Bulk actions_ button allows users to perform bulk actions for selected stores (using the checkboxes). A user can:
```suggestion
Clicking on the _Bulk actions_ button allows users to perform bulk actions for selected tags (using the checkboxes). A user can:
```

2021-11-29 17:19 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +- Delete selected: This button will delete the selected stores.
```suggestion
- Delete selected: This button will delete the selected tags. 
```

2021-11-29 17:21 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +When trying to delete the selection without any checkboxes checked, the following message is displayed: "You must select at least one element to delete."
```suggestion

```

2021-11-29 17:22 UTC, marionf commented on content/1.7/back-office/shop-parameters/search/tags/tags-listing.md
> +When trying to delete the selection without any checkboxes checked, the following message is displayed: "You must select at least one element to delete."
On migrated pages, the Bulk actions button is enabled only if at least one row of the list is selected, so this case can't happen

2021-11-30 10:39 UTC, marwachelly approved these changes
PR Can be merged. Thanks @marionf , @Saimis777

2021-11-30 10:44 UTC, merged